In [9]:
import pandas as pd

wc_data = pd.read_excel('WC_train1.xlsx', index_col=None)
wc_data.to_csv('WC_train1.csv', encoding='utf-8', index=False)

In [10]:
import pandas as pd
import pandas_profiling
wc_data.describe()

              Year
count  2640.000000
mean   2003.701515
std       8.972798
min    1987.000000
25%    1997.000000
50%    2004.000000
75%    2011.000000
max    2019.000000

In [11]:
wc_data.keys()

Index(['Month', 'Year', 'Team A', 'Team B', 'Ground', 'Won'], dtype='object')

In [12]:
wc_data['Won'] = (wc_data['Team A'] == wc_data['Won']).astype(int)
wc_data = wc_data.rename({'Won': 'Team_A_Won'}, axis=1)
wc_data

,Month,Year,Team A,Team B,Ground,Team_A_Won
0,January,1987,England,West Indies,Adelaide Oval,1
1,January,1987,Australia,West Indies,Adelaide Oval,0
2,January,1987,Australia,England,Adelaide Oval,1
3,March,1987,New Zealand,West Indies,AMI Stadium,0
4,October,1987,England,Sri Lanka,Arbab Niaz Stadium,1
5,November,1987,Pakistan,England,Arbab Niaz Stadium,0
6,January,1987,England,West Indies,Brisbane Cricket Ground,1
7,January,1987,Australia,England,Brisbane Cricket Ground,1
8,March,1987,New Zealand,West Indies,Carisbrook,0
9,February,1987,England,West Indies,Devonport Oval,1
10,February,1987,India,Pakistan,Eden Gardens,0
11,November,1987,Australia,England,Eden Gardens,1
12,March,1987,New Zealand,West Indies,Eden Park,0
13,May,1987,England,Pakistan,Edgbaston,1
14,January,1987,India,Sri Lanka,Feroz Shah Kotla,1
15,October,1987,India,Australia,Feroz Shah Kotla,1
16,November,1987,Pakistan,England,Gaddafi Stadium,0
17,October,1987,Pakistan,West Indies,Gaddafi Stadium,1
18,November,1987,Pakistan,Australia,Gaddafi Stadium,0
19,October,1987,Sri Lanka,West Indies,Green Park,0
20,October,1987,Pakistan,Sri Lanka,Iqbal Stadium,1
21,October,1987,England,West Indies,Jinnah Stadium,1
22,March,1987,India,Pakistan,Keenan Stadium,0
23,May,1987,England,Pakistan,Kennington Oval,1
24,March,1987,India,Pakistan,Lal Bahadur Shastri Stadium,1
25,October,1987,India,New Zealand,M Chinnaswamy Stadium,1
26,October,1987,India,Australia,MA Chidambaram Stadium,0
27,February,1987,Australia,England,Melbourne Cricket Ground,0
28,January,1987,Australia,West Indies,Melbourne Cricket Ground,0
29,January,1987,England,West Indies,Melbourne Cricket Ground,0
...,...,...,...,...,...,...
2610,June,2019,India,New Zealand,Nottingham,0
2611,June,2019,England,West Indies,Southampton,1
2612,June,2019,Australia,Sri Lanka,The Oval,1
2613,June,2019,Afghanistan,South Africa,Cardiff,0
2614,June,2019,India,Pakistan,Manchester,1
2615,June,2019,Bangladesh,West Indies,Taunton,1
2616,June,2019,England,Afghanistan,Manchester,1
2617,June,2019,New Zealand,South Africa,Birmingham,1
2618,June,2019,Australia,Bangladesh,Nottingham,1
2619,June,2019,England,Sri Lanka,Leeds,0
2620,June,2019,Afghanistan,India,Southampton,0
2621,June,2019,New Zealand,West Indies,Manchester,1
2622,June,2019,Pakistan,South Africa,Lord's,1
2623,June,2019,Afghanistan,Bangladesh,Southampton,0
2624,June,2019,England,Australia,Lord's,0
2625,June,2019,New Zealand,Pakistan,Birmingham,0
2626,June,2019,India,West Indies,Manchester,1
2627,June,2019,South Africa,Sri Lanka,Chester-le-Street,1
2628,June,2019,Afghanistan,Pakistan,Leeds,0
2629,June,2019,Australia,New Zealand,Lord's,1
2630,June,2019,England,India,Birmingham,1
2631,June,2019,Sri Lanka,West Indies,Chester-le-Street,1
2632,June,2019,Bangladesh,India,Birmingham,0
2633,June,2019,England,New Zealand,Chester-le-Street,1
2634,June,2019,Afghanistan,West Indies,Leeds,0
2635,June,2019,Bangladesh,Pakistan,Lord's,0
2636,June,2019,India,Sri Lanka,Leeds,1
2637,June,2019,Australia,South Africa,Manchester,0
2638,July,2019,India,New Zealand,Manchester,1
2639,July,2019,Australia,England,Birmingham,1

In [13]:
wc_data

,Month,Year,Team A,Team B,Ground,Team_A_Won
0,January,1987,England,West Indies,Adelaide Oval,1
1,January,1987,Australia,West Indies,Adelaide Oval,0
2,January,1987,Australia,England,Adelaide Oval,1
3,March,1987,New Zealand,West Indies,AMI Stadium,0
4,October,1987,England,Sri Lanka,Arbab Niaz Stadium,1
5,November,1987,Pakistan,England,Arbab Niaz Stadium,0
6,January,1987,England,West Indies,Brisbane Cricket Ground,1
7,January,1987,Australia,England,Brisbane Cricket Ground,1
8,March,1987,New Zealand,West Indies,Carisbrook,0
9,February,1987,England,West Indies,Devonport Oval,1
10,February,1987,India,Pakistan,Eden Gardens,0
11,November,1987,Australia,England,Eden Gardens,1
12,March,1987,New Zealand,West Indies,Eden Park,0
13,May,1987,England,Pakistan,Edgbaston,1
14,January,1987,India,Sri Lanka,Feroz Shah Kotla,1
15,October,1987,India,Australia,Feroz Shah Kotla,1
16,November,1987,Pakistan,England,Gaddafi Stadium,0
17,October,1987,Pakistan,West Indies,Gaddafi Stadium,1
18,November,1987,Pakistan,Australia,Gaddafi Stadium,0
19,October,1987,Sri Lanka,West Indies,Green Park,0
20,October,1987,Pakistan,Sri Lanka,Iqbal Stadium,1
21,October,1987,England,West Indies,Jinnah Stadium,1
22,March,1987,India,Pakistan,Keenan Stadium,0
23,May,1987,England,Pakistan,Kennington Oval,1
24,March,1987,India,Pakistan,Lal Bahadur Shastri Stadium,1
25,October,1987,India,New Zealand,M Chinnaswamy Stadium,1
26,October,1987,India,Australia,MA Chidambaram Stadium,0
27,February,1987,Australia,England,Melbourne Cricket Ground,0
28,January,1987,Australia,West Indies,Melbourne Cricket Ground,0
29,January,1987,England,West Indies,Melbourne Cricket Ground,0
...,...,...,...,...,...,...
2610,June,2019,India,New Zealand,Nottingham,0
2611,June,2019,England,West Indies,Southampton,1
2612,June,2019,Australia,Sri Lanka,The Oval,1
2613,June,2019,Afghanistan,South Africa,Cardiff,0
2614,June,2019,India,Pakistan,Manchester,1
2615,June,2019,Bangladesh,West Indies,Taunton,1
2616,June,2019,England,Afghanistan,Manchester,1
2617,June,2019,New Zealand,South Africa,Birmingham,1
2618,June,2019,Australia,Bangladesh,Nottingham,1
2619,June,2019,England,Sri Lanka,Leeds,0
2620,June,2019,Afghanistan,India,Southampton,0
2621,June,2019,New Zealand,West Indies,Manchester,1
2622,June,2019,Pakistan,South Africa,Lord's,1
2623,June,2019,Afghanistan,Bangladesh,Southampton,0
2624,June,2019,England,Australia,Lord's,0
2625,June,2019,New Zealand,Pakistan,Birmingham,0
2626,June,2019,India,West Indies,Manchester,1
2627,June,2019,South Africa,Sri Lanka,Chester-le-Street,1
2628,June,2019,Afghanistan,Pakistan,Leeds,0
2629,June,2019,Australia,New Zealand,Lord's,1
2630,June,2019,England,India,Birmingham,1
2631,June,2019,Sri Lanka,West Indies,Chester-le-Street,1
2632,June,2019,Bangladesh,India,Birmingham,0
2633,June,2019,England,New Zealand,Chester-le-Street,1
2634,June,2019,Afghanistan,West Indies,Leeds,0
2635,June,2019,Bangladesh,Pakistan,Lord's,0
2636,June,2019,India,Sri Lanka,Leeds,1
2637,June,2019,Australia,South Africa,Manchester,0
2638,July,2019,India,New Zealand,Manchester,1
2639,July,2019,Australia,England,Birmingham,1

In [14]:
# Print full description by running:
# print(cancer['DESCR'])
# 569 data points with 30 features
wc_data.shape

(2640, 6)

In [15]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder

# define example
# integer encode
label_encoder = LabelEncoder()
#wc_data['Month'] = label_encoder.fit_transform(wc_data['Month'])
#wc_data['Year'] = label_encoder.fit_transform(wc_data['Year'])
#wc_data['Team A'] = label_encoder.fit_transform(wc_data['Team A'])
#wc_data['Team B'] = label_encoder.fit_transform(wc_data['Team B'])
#wc_data['Ground'] = label_encoder.fit_transform(wc_data['Ground'])

df_encoded = wc_data.apply(label_encoder.fit_transform)

print(df_encoded)

      Month  Year  Team A  Team B  Ground  Team_A_Won
0         4     0       6       9       1           1
1         4     0       2       9       1           0
2         4     0       2       3       1           1
3         7     0      10       9       0           0
4        10     0       6       8       3           1
5         9     0      12       3       3           0
6         4     0       6       9      18           1
7         4     0       2       3      18           1
8         7     0      10       9      23           0
9         3     0       6       9      33           1
10        3     0       8       6      38           0
11        9     0       2       3      38           1
12        7     0      10       9      39           0
13        8     0       6       6      40           1
14        4     0       8       8      42           1
15       10     0       8       1      42           1
16        9     0      12       3      43           0
17       10     0      12       9      43           1
18        9     0      12       1      43           0
19       10     0      16       9      47           0
20       10     0      12       8      58           1
21       10     0       6       9      61           1
22        7     0       8       6      64           0
23        8     0       6       6      65           1
24        7     0       8       6      70           1
25       10     0       8       5      73           1
26       10     0       8       1      75           0
27        3     0       2       3      84           0
28        4     0       2       9      84           0
29        4     0       6       9      84           0
...     ...   ...     ...     ...     ...         ...
2610      6    32       7       5      95           0
2611      6    32       5       9     130           1
2612      6    32       1       8     138           1
2613      6    32       0       7      22           0
2614      6    32       7       6      79           1
2615      6    32       3       9     137           1
2616      6    32       5       0      79           1
2617      6    32       9       7      14           1
2618      6    32       1       2      95           1
2619      6    32       5       8      71           0
2620      6    32       0       4     130           0
2621      6    32       9       9      79           1
2622      6    32      11       7      72           1
2623      6    32       0       2     130           0
2624      6    32       5       1      72           0
2625      6    32       9       6      14           0
2626      6    32       7       9      79           1
2627      6    32      13       8      26           1
2628      6    32       0       6      71           0
2629      6    32       1       5      72           1
2630      6    32       5       4      14           1
2631      6    32      15       9      26           1
2632      6    32       3       4      14           0
2633      6    32       5       5      26           1
2634      6    32       0       9      71           0
2635      6    32       3       6      72           0
2636      6    32       7       8      71           1
2637      6    32       1       7      79           0
2638      5    32       7       5      79           1
2639      5    32       1       3      14           1

[2640 rows x 6 columns]

In [16]:
X = df_encoded.iloc[:, :5]
Y = df_encoded.iloc[:, 5:]

###############################
#For Semifinal Test Cases as Label Encoder
# 5 = JUly
# 32 = 2019
# 7 = India, 5 = New Zealand , 1 = Australia, 3 = England
# 79 = Manchester, 14 = Birmingham

#In the dataset, I have filled up result as per my intuitions
# X1 is test case for semifinal

X1 = [[5,32,7,5,79],[5,32,1,3,14]]

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.2)

In [34]:
from matplotlib import pyplot as plt
from sklearn import datasets, linear_model

In [35]:
X_test

      Month  Year  Team A  Team B  Ground
364       9     6      16       9      38
2585      8    32       4       9     140
1485      4    19       2       8      41
178       4     2       2       6     148
537       3     8       8       7     120
927       6    13      12       8       6
2127      3    26       2       9      84
1602      5    20       6       9      72
1360      5    17      16       4     110
791       0    11       2       4     123
503       2     8      16       9       1
2314      6    28       4       4     126
2425     10    30       8       5      47
397       3     6      12       8     123
1787      3    22      16       4     108
1855      9    23      12       7      36
2209      4    27      10       4      83
2030      4    25      14       8      34
2270      6    28       6       5      40
1221      3    16      16       2      27
829       8    12      10       6      30
2229      4    27      10       9     118
1005      3    13       2       6     135
1275      2    16      12       5     111
1651      7    20      17       1     128
729       4    10      12       9     135
102       3     1       2       3      84
1159     11    15       8       7     108
1857      7    23      10       1      39
1667      4    20       6       5     148
...     ...   ...     ...     ...     ...
1152      0    15      14       1      93
1394      3    18      14       3      20
39       10     0       2       5      92
937      10    13      14       5      34
602      10     9       2       7      92
2019      7    25      17       1       4
1793     11    22      16       5     108
276       2     4       2       9     135
1253      6    16      17       1      89
887       1    12      16       1     108
2073      7    25      12       8     126
2426      3    30      10       7      50
2297      5    28      16       6     108
1705      6    21      12       4      91
2038     11    25       6       7      72
1503     11    19       8       9      69
2321      1    28      14       5     134
1464      4    18      14       3     149
638      11     9       2       4     127
1631      5    20      16       2     108
1743      3    21      14       9     149
872       3    12       2       8      84
1903      4    23       8       8     126
1484     11    19       6       6      40
2208      9    27       2       7      81
2446      3    30      14       8      93
1980      0    24       4       1     126
1722      6    21       6       5     113
27        3     0       2       3      84
137      10     2       6       9      21

[528 rows x 5 columns]

In [36]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(2112, 5) (2112, 1)
(528, 5) (528, 1)

In [37]:
# fit a model
#lm = linear_model.LinearRegression()
#model = lm.fit(X_train, y_train)
#predictions = lm.predict(X_test)

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [39]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X1 = scaler.transform(X1)

In [40]:

from sklearn.neural_network import MLPClassifier

In [41]:

mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))

In [42]:
mlp.fit(X_train,y_train)

C:\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:950: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:587: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(30, 30, 30), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [43]:

predictions = mlp.predict(X_test)
predictions1 = mlp.predict(X1)

In [44]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[135 108]
 [ 98 187]]

In [45]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.58      0.56      0.57       243
           1       0.63      0.66      0.64       285

    accuracy                           0.61       528
   macro avg       0.61      0.61      0.61       528
weighted avg       0.61      0.61      0.61       528

In [46]:
predictions1

array([1, 1], dtype=int64)

In [32]:
#####
#Here it is prediction Team A win for both
#In our test case, Team A is India and Australia